CREATE TABLE IF NOT EXISTS required_artifact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    milestone_id BIGINT NOT NULL,
    type VARCHAR(16) NOT NULL,
    label VARCHAR(100) NOT NULL,
    is_required BOOLEAN NOT NULL,
    allowed_extensions VARCHAR(255),
    max_file_size_mb INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT ck_required_artifact_type CHECK (type IN ('FILE', 'LINK', 'TEXT', 'CHEERPJ_RUN')),
    CONSTRAINT ck_required_artifact_max_file_size_positive CHECK (max_file_size_mb IS NULL OR max_file_size_mb > 0)
);

CREATE INDEX IF NOT EXISTS idx_required_artifact_milestone
    ON required_artifact (milestone_id);

COMMENT ON COLUMN required_artifact.milestone_id IS 'Milestone 외부 FK는 Milestone 테이블 도입 후 적용한다.';

CREATE TABLE IF NOT EXISTS review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT NOT NULL,
    reviewer_id VARCHAR(16) NOT NULL,
    result_status VARCHAR(32) NOT NULL,
    comment VARCHAR(2000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT ck_review_result_status CHECK (result_status IN ('APPROVED', 'FEEDBACK_PROVIDED', 'REVISION_REQUESTED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_review_active_version
    ON review (version_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_review_reviewer
    ON review (reviewer_id);

COMMENT ON COLUMN review.version_id IS 'SubmissionVersion 외부 FK는 SubmissionVersion 테이블 도입 후 적용한다.';
COMMENT ON COLUMN review.reviewer_id IS 'User 외부 FK는 User 테이블 도입 후 적용한다.';

CREATE TABLE IF NOT EXISTS mid_report_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    author_id VARCHAR(16) NOT NULL,
    onsite_feedback_summary VARCHAR(2000) NOT NULL,
    professor_additional_feedback VARCHAR(2000),
    revision_note VARCHAR(2000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_mid_report_feedback_active_submission_author
    ON mid_report_feedback (submission_id, author_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_mid_report_feedback_submission
    ON mid_report_feedback (submission_id);

CREATE INDEX IF NOT EXISTS idx_mid_report_feedback_author
    ON mid_report_feedback (author_id);

COMMENT ON COLUMN mid_report_feedback.submission_id IS 'Submission 외부 FK는 Submission 테이블 도입 후 적용한다.';
COMMENT ON COLUMN mid_report_feedback.author_id IS 'User 외부 FK는 User 테이블 도입 후 적용한다.';
