-- EnrollmentJpaEntity 에서 Hibernate 로 생성한 DDL (PostgreSQLDialect).
-- 컨벤션에 맞춰 IF NOT EXISTS 와 주석, 부분 유니크 인덱스만 추가했다.
CREATE TABLE IF NOT EXISTS "enrollment" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL,
    section_id BIGINT NOT NULL,
    user_id VARCHAR(20) NOT NULL,
    role VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    PRIMARY KEY (id)
);

-- 살아있는 수강 정보는 (분반, 학번)당 하나. createEnrollment 의 존재 확인 후 저장은
-- check-then-act 이라 동시 요청을 막지 못하므로, 중복 차단의 최종 근거는 이 인덱스다.
-- 위반 시 DataIntegrityViolationException 이 GlobalExceptionHandler 에서 409 로 매핑된다.
-- 소프트 삭제된 행은 제외해야 재등록이 막히지 않으므로 JPA 유니크 제약 대신 부분 인덱스를 쓴다.
CREATE UNIQUE INDEX IF NOT EXISTS uk_enrollment_active_section_user
    ON "enrollment" (section_id, user_id)
    WHERE deleted_at IS NULL;
