-- EnrollmentJpaEntity 에서 Hibernate 로 생성한 DDL (PostgreSQLDialect).
-- 컨벤션에 맞춰 IF NOT EXISTS 와 주석만 추가했다.
-- 이 파일은 문서다. 실행하는 코드도 설정도 없으므로, 실제 스키마의 근거는 JPA 애노테이션이다.
CREATE TABLE IF NOT EXISTS "enrollment" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL,
    section_id BIGINT NOT NULL,
    user_id VARCHAR(20) NOT NULL,
    role VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    PRIMARY KEY (id),
    -- 살아있는 수강 정보는 (분반, 학번)당 하나. createEnrollment 의 존재 확인 후 저장은
    -- check-then-act 이라 동시 요청을 막지 못하므로, 중복 차단의 최종 근거는 이 제약이다.
    -- 위반 시 DataIntegrityViolationException 이 GlobalExceptionHandler 에서 409 로 매핑된다.
    --
    -- deleted_at 을 무시하는 일반 유니크 제약인데도 재등록이 막히지 않는 이유는,
    -- createEnrollment 가 소프트 삭제된 이력을 찾으면 INSERT 대신 그 행을 재활성화하기 때문이다.
    -- 즉 (section_id, user_id) 당 행은 영원히 하나이고, 그래서 부분 인덱스가 필요 없다.
    -- 이 불변식이 깨지면(재활성화를 걷어내면) 제약도 함께 바꿔야 한다.
    CONSTRAINT uk_enrollment_section_user UNIQUE (section_id, user_id)
);
