-- ImportBatchJpaEntity 에서 Hibernate 로 생성한 DDL (PostgreSQLDialect).
-- 컨벤션에 맞춰 IF NOT EXISTS 와 주석을 추가하고, FK 는 CREATE TABLE 안으로 옮겼다.
CREATE TABLE IF NOT EXISTS "import_batch" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL,
    expired_at TIMESTAMP(6) NOT NULL,
    payload JSONB NOT NULL,
    section_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('PREVIEW', 'APPLIED', 'EXPIRED')),
    summary JSONB NOT NULL,
    type VARCHAR(16) NOT NULL CHECK (type IN ('ENROLLMENT', 'TEAM')),
    uploaded_by VARCHAR(20) NOT NULL,
    version BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_import_batch_section
        FOREIGN KEY (section_id) REFERENCES section (id),
    CONSTRAINT fk_import_batch_uploader
        FOREIGN KEY (uploaded_by) REFERENCES "user" (student_number)
);

CREATE INDEX IF NOT EXISTS idx_import_batch_section
    ON "import_batch" (section_id, deleted_at);

COMMENT ON COLUMN "import_batch".payload IS '업로드된 시트 {headers, rows[]}. ImportPayload 와 1:1.';
COMMENT ON COLUMN "import_batch".summary IS '미리보기 요약 {total, created, updated, skipped, invalid}.';
COMMENT ON COLUMN "import_batch".version IS '낙관적 락. Hibernate 가 채우므로 수동 INSERT 금지.';
