-- ImportBatchJpaEntity 에서 Hibernate 로 생성한 DDL (PostgreSQLDialect).
-- 컨벤션에 맞춰 IF NOT EXISTS 와 주석만 추가했고, 컬럼 정의는 생성된 그대로다.
CREATE TABLE IF NOT EXISTS "import_batch" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL,
    expired_at TIMESTAMP(6) NOT NULL,
    payload JSONB NOT NULL,
    section_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (status IN ('PREVIEW', 'APPLIED', 'EXPIRED')),
    summary JSONB NOT NULL,
    type VARCHAR(16) NOT NULL CHECK (type IN ('ENROLLMENT', 'TEAM')),
    uploaded_by VARCHAR(20) NOT NULL,
    version BIGINT,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_import_batch_section
    ON "import_batch" (section_id, deleted_at);

COMMENT ON COLUMN "import_batch".section_id IS 'Section 외부 FK는 Section 테이블 도입 후 적용한다.';
COMMENT ON COLUMN "import_batch".payload IS '업로드된 시트 {headers, rows[]}. ImportPayload 와 1:1.';
COMMENT ON COLUMN "import_batch".summary IS '미리보기 요약 {total, created, updated, skipped, invalid}.';
COMMENT ON COLUMN "import_batch".version IS '낙관적 락. Hibernate 가 채우므로 수동 INSERT 금지.';
