CREATE TABLE IF NOT EXISTS milestone (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    week_number INTEGER NOT NULL CHECK (week_number > 0),
    status VARCHAR(16) NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED')),
    opens_at TIMESTAMP,
    due_at TIMESTAMP NOT NULL,
    late_submission_until TIMESTAMP,
    revision_until TIMESTAMP,
    evaluation_opens_at TIMESTAMP,
    evaluation_closes_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_milestone_active_section_week
    ON milestone (section_id, week_number)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_milestone_section_status_week
    ON milestone (section_id, status, week_number);

-- Add the section foreign key after the section table contract is merged.
