CREATE TABLE IF NOT EXISTS milestone (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    week_number INTEGER NOT NULL CHECK (week_number > 0),
    status VARCHAR(16) NOT NULL,
    opens_at TIMESTAMP,
    due_at TIMESTAMP NOT NULL,
    late_submission_until TIMESTAMP,
    revision_until TIMESTAMP,
    evaluation_opens_at TIMESTAMP,
    evaluation_closes_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

-- 기존 테이블의 자동 생성 제약(DRAFT, PUBLISHED)도 CLOSED를 허용하도록 교체한다.
-- 명시적 제약명도 먼저 제거하므로 이 스크립트는 반복 실행할 수 있다.
ALTER TABLE milestone DROP CONSTRAINT IF EXISTS milestone_status_check;
ALTER TABLE milestone DROP CONSTRAINT IF EXISTS chk_milestone_status;
ALTER TABLE milestone ADD CONSTRAINT chk_milestone_status
    CHECK (status IN ('DRAFT', 'PUBLISHED', 'CLOSED'));

CREATE UNIQUE INDEX IF NOT EXISTS uq_milestone_active_section_week
    ON milestone (section_id, week_number)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_milestone_section_status_week
    ON milestone (section_id, status, week_number);

-- Add the section foreign key after the section table contract is merged.
