-- PreSurveyResponseJpaEntity 에서 Hibernate 로 생성한 DDL (PostgreSQLDialect).
-- 컨벤션에 맞춰 IF NOT EXISTS 와 주석, 부분 유니크 인덱스만 추가했다.
CREATE TABLE IF NOT EXISTS "pre_survey_response" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL,
    submitted_at TIMESTAMP(6) NOT NULL,
    user_id VARCHAR(20) NOT NULL,
    section_id BIGINT NOT NULL,
    preferred_roles JSONB NOT NULL,
    topic_opinion TEXT,
    etc_opinion TEXT,
    preferred_peer_user_id VARCHAR(20),
    preferred_peer_status VARCHAR(20)
        CONSTRAINT ck_pre_survey_response_preferred_peer_status
        CHECK (preferred_peer_status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    PRIMARY KEY (id),
    -- 자기 자신은 조원으로 지목할 수 없다. IS DISTINCT FROM 이라 지목이 없는(NULL) 행은 통과한다.
    CONSTRAINT ck_pre_survey_response_preferred_peer_not_self
        CHECK (preferred_peer_user_id IS DISTINCT FROM user_id),
    -- 지목 대상과 상태는 항상 같이 있거나 같이 없다.
    CONSTRAINT ck_pre_survey_response_preferred_peer_paired
        CHECK ((preferred_peer_user_id IS NULL) = (preferred_peer_status IS NULL))
);

-- 살아있는 응답은 (학번, 분반)당 하나. findByUserIdAndSectionId 가 Optional 을 돌려줄 수 있는 근거다.
-- 소프트 삭제된 행은 제외해야 재제출이 막히지 않으므로 JPA 유니크 제약 대신 부분 인덱스를 쓴다.
CREATE UNIQUE INDEX IF NOT EXISTS uk_pre_survey_response_active_user_section
    ON "pre_survey_response" (user_id, section_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_pre_survey_response_section
    ON "pre_survey_response" (section_id, deleted_at);

-- 나를 지목한 응답을 찾는 조회(수락·거절 목록)의 인덱스다.
CREATE INDEX IF NOT EXISTS idx_pre_survey_response_preferred_peer
    ON "pre_survey_response" (section_id, preferred_peer_user_id, deleted_at);

COMMENT ON COLUMN "pre_survey_response".user_id IS 'User 외부 FK는 User 테이블 도입 후 적용한다.';
COMMENT ON COLUMN "pre_survey_response".section_id IS 'Section 외부 FK는 Section 테이블 도입 후 적용한다.';
COMMENT ON COLUMN "pre_survey_response".preferred_roles IS '희망 역할 JSON. 형식은 도메인이 강제하지 않는다.';
COMMENT ON COLUMN "pre_survey_response".preferred_peer_user_id IS '조원으로 희망해 지목한 학생 학번. 1명뿐이라 별도 테이블을 두지 않는다.';
COMMENT ON COLUMN "pre_survey_response".preferred_peer_status IS 'PENDING/ACCEPTED/REJECTED. 지목이 없으면 NULL.';
