CREATE TABLE IF NOT EXISTS project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    goal TEXT NOT NULL,
    repository_url VARCHAR(255),
    external_links JSONB,
    approval_status VARCHAR(50) NOT NULL,
    meeting_style VARCHAR(200),
    proposal_completed_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT fk_team_project FOREIGN KEY (team_id) REFERENCES team(id)
);

-- 부분 유니크 인덱스: 팀당 활성 프로젝트 1개 보장 (deleted_at IS NULL인 경우만)
CREATE UNIQUE INDEX IF NOT EXISTS uk_project_team_active 
ON project (team_id) 
WHERE deleted_at IS NULL;

-- 일반 인덱스
CREATE INDEX IF NOT EXISTS idx_project_team ON project (team_id);
CREATE INDEX IF NOT EXISTS idx_project_approval_status ON project (approval_status);
