CREATE TABLE IF NOT EXISTS project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    topic_candidate_id BIGINT,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    goal TEXT NOT NULL,
    data_configuration JSONB,
    screen_configuration JSONB,
    key_features JSONB NOT NULL DEFAULT '[]'::jsonb,
    demo_flow JSONB NOT NULL DEFAULT '[]'::jsonb,
    project_schedule TEXT,
    repository_url VARCHAR(255),
    external_links JSONB,
    approval_status VARCHAR(50) NOT NULL,
    proposal_completed_at TIMESTAMP,
    -- 제안서 내용이 바뀔 때마다 증가한다. 이전 리비전의 동의는 무효가 된다.
    proposal_revision BIGINT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT fk_team_project FOREIGN KEY (team_id) REFERENCES team(id)
);

-- CREATE TABLE IF NOT EXISTS는 기존 테이블에 열을 추가하지 않는다. 기존 제안서의 주요 기능·시연 흐름은
-- 빈 배열로 채워 새 JSONB 매핑과 동일한 기본값을 보장하고, 일정은 선택값이라 NULL을 유지한다.
ALTER TABLE project ADD COLUMN IF NOT EXISTS key_features JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE project ADD COLUMN IF NOT EXISTS demo_flow JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE project ADD COLUMN IF NOT EXISTS project_schedule TEXT;
UPDATE project SET key_features = '[]'::jsonb WHERE key_features IS NULL;
UPDATE project SET demo_flow = '[]'::jsonb WHERE demo_flow IS NULL;
ALTER TABLE project ALTER COLUMN key_features SET DEFAULT '[]'::jsonb;
ALTER TABLE project ALTER COLUMN demo_flow SET DEFAULT '[]'::jsonb;
ALTER TABLE project ALTER COLUMN key_features SET NOT NULL;
ALTER TABLE project ALTER COLUMN demo_flow SET NOT NULL;

-- KD3-211 이전에는 data_configuration 이 TEXT 였다. NULL·공백은 빈 배열로, 이미 저장된 JSON 배열은
-- 그대로 옮긴다. 그 외에는 배열 항목으로 추측 변환할 수 없으므로 실패시켜 운영자가 원본을 확인하게 한다.
CREATE OR REPLACE FUNCTION pg_temp.to_jsonb_array(value TEXT)
RETURNS JSONB
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
    parsed JSONB;
BEGIN
    IF value IS NULL OR btrim(value) = '' THEN
        RETURN '[]'::JSONB;
    END IF;

    parsed := value::JSONB;
    IF jsonb_typeof(parsed) <> 'array' THEN
        RAISE EXCEPTION 'project.data_configuration must be a JSON array';
    END IF;
    RETURN parsed;
END;
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'project'
          AND column_name = 'data_configuration'
          AND data_type <> 'jsonb'
    ) THEN
        ALTER TABLE project
            ALTER COLUMN data_configuration TYPE JSONB
            USING pg_temp.to_jsonb_array(data_configuration);
    END IF;
END;
$$;

-- 부분 유니크 인덱스: 팀당 활성 프로젝트 1개 보장 (deleted_at IS NULL인 경우만)
CREATE UNIQUE INDEX IF NOT EXISTS uk_project_team_active 
ON project (team_id) 
WHERE deleted_at IS NULL;

-- 일반 인덱스
CREATE INDEX IF NOT EXISTS idx_project_team ON project (team_id);
CREATE INDEX IF NOT EXISTS idx_project_approval_status ON project (approval_status);
