--- TeamJpaEntity에서 Hibernate로 생성한 DDL (PostgreSQLDialect)
--- 컨벤션에 맞춰 IF NOT EXISTS와 주석을 추가하고, FK는 CREATE TABLE 안으로 옮겼다.
CREATE TABLE IF NOT EXISTS team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    version BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    kickoff_rule TEXT NOT NULL,
    meeting_schedule TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT fk_section_team FOREIGN KEY (section_id) REFERENCES section (id),
    CONSTRAINT uk_team_section_name UNIQUE (section_id, name)
);

CREATE INDEX IF NOT EXISTS idx_team_section ON team (section_id);
