--- TeamMemberJpaEntity에서 Hibernate로 생성한 DDL (PostgreSQLDialect)
--- 컨벤션에 맞춰 IF NOT EXISTS와 주석을 추가하고, FK는 CREATE TABLE 안으로 옮겼다.
--- uk_team_member_one_leader는 부분 유니크 인덱스로 분리하여 활성 팀장(is_leader=true, deleted_at IS NULL)에만 적용한다.
CREATE TABLE IF NOT EXISTS team_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    version BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_leader BOOLEAN NOT NULL,
    project_role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    CONSTRAINT fk_team_member_team FOREIGN KEY (team_id) REFERENCES team (id),
    CONSTRAINT fk_team_member_user FOREIGN KEY (user_id) REFERENCES "user" (id),
    CONSTRAINT uk_team_member_team_user UNIQUE (team_id, user_id)
);

-- 활성 팀장(is_leader=true, deleted_at IS NULL)에만 적용되는 부분 유니크 인덱스
-- 같은 팀의 비팀원(is_leader=false)이 여러 명 존재할 수 있도록 허용한다.
CREATE UNIQUE INDEX IF NOT EXISTS uk_team_member_one_leader
    ON team_member (team_id, is_leader)
    WHERE is_leader = true AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_team_member_team ON team_member (team_id);
CREATE INDEX IF NOT EXISTS idx_team_member_user ON team_member (user_id);
