-- TopicVoteJpaEntity 에서 Hibernate 로 생성한 DDL (PostgreSQLDialect).
-- 컨벤션에 맞춰 IF NOT EXISTS 와 주석만 추가했다.
-- 이 파일은 문서다. 실행하는 코드도 설정도 없으므로, 실제 스키마의 근거는 JPA 애노테이션이다.
CREATE TABLE IF NOT EXISTS topic_vote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL,
    team_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    voter_user_id VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    -- 팀 안에서 한 사람은 한 표. 후보가 아니라 팀이 1인 1표의 범위이므로 team_id 로 묶는다.
    -- (candidate_id, voter_user_id) 로 묶으면 한 사람이 여러 후보에 동시 투표할 수 있어 의도를 못 지킨다.
    -- TopicVoteCommandService.vote 의 존재 확인 후 저장은 check-then-act 이라 동시 요청을 막지 못하므로,
    -- 중복 차단의 최종 근거는 이 제약이다.
    -- 위반 시 DataIntegrityViolationException 이 GlobalExceptionHandler 에서 409 로 매핑된다.
    --
    -- deleted_at 을 무시하는 일반 유니크 제약인데도 재투표가 막히지 않는 이유는,
    -- vote 가 소프트 삭제된 이력을 찾으면 INSERT 대신 그 행을 재활성화하기 때문이다.
    -- 투표 변경도 새 행이 아니라 같은 행의 candidate_id 갱신이다.
    -- 즉 (team_id, voter_user_id) 당 행은 영원히 하나이고, 그래서 부분 인덱스가 필요 없다.
    -- 이 불변식이 깨지면(재활성화를 걷어내면) 제약도 함께 바꿔야 한다. enrollment.sql 과 동일한 규약이다.
    CONSTRAINT uk_topic_vote_team_voter UNIQUE (team_id, voter_user_id)
);

-- 후보별 득표 집계용
CREATE INDEX IF NOT EXISTS idx_topic_vote_candidate ON topic_vote (candidate_id, deleted_at);
