server:
  port: 8081

spring:
  application:
    name: aics-server

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:aics}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        jdbc:
          time_zone: Asia/Seoul
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

file:
   url: /cloud
   upload-path: ${FILE_UPLOAD_PATH:./cloud}
   secret-key: ${FILE_SECRET_KEY:secret-key}
   disallowed-extensions: exe, bat, sh, cmd, js, html, jsp, php, asp, aspx, dll, so, ps1, vbs, msi, htaccess, phtml, jar, war

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

jwt:
  issuer: ${JWT_ISSUER:kgudevelopers@gmail.com}
  secret_key: ${JWT_SECRET_KEY:c2VjcmV0LWtleS1zZWNyZXQta2V5LXNlY3JldC1rZXktc2VjcmV0LWtleQ==}

docs:
  admin-docs-url: ${ADMIN_DOCS_URL:http://localhost:8081/swagger-ui/index.html}
  api-docs-url: ${API_DOCS_URL:http://localhost:8080/swagger-ui/index.html}
  auth-docs-url: ${AUTH_DOCS_URL:http://localhost:8082/swagger-ui/index.html}