spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  data:
    redis:
      password: ${REDIS_PASSWORD:}

  security:
    user:
      name: admin
      # bcrypt 해시 평문은 "admin".
      password: "$2a$10$nKxI21dQHbHpp4SRpVmIBOp1j6YjpAE0GW79cVz.6M01em.9TTXjm"
      roles: ADMIN

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

file:
  secret-key: ${FILE_SECRET_KEY}

jwt:
  secret_key: ${JWT_SECRET_KEY}
