name: Build and Deploy to Development Server on Cloud

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    environment: cloud-dev

    steps:
      - name: get repo from github
        uses: actions/checkout@v4

      # JDK setting
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # gradle 빌드
      - name: Setup Gradle
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: |
          ./gradlew clean build -p aics-admin -x test
          ./gradlew clean build -p aics-api -x test
          ./gradlew clean build -p aics-auth -x test

      # DockerHub 로그인
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Docker 이미지 빌드
      - name: Docker image build for aics-admin
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/aics-admin:${{ github.sha }} -f aics-admin/Dockerfile .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/aics-admin:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/aics-admin:latest

      - name: Docker image build for aics-api
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/aics-api:${{ github.sha }} -f aics-api/Dockerfile .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/aics-api:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/aics-api:latest

      - name: Docker image build for aics-auth
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/aics-auth:${{ github.sha }} -f aics-auth/Dockerfile .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/aics-auth:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/aics-auth:latest

      # Docker Hub 이미지 푸시
      - name: docker Hub push for aics-admin
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aics-admin:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aics-admin:latest

      - name: docker Hub push for aics-api
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aics-api:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aics-api:latest

      - name: docker Hub push for aics-auth
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aics-auth:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aics-auth:latest

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: build-docker-image
    environment: cloud-dev

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: scp docker-compose and Caddyfile to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "docker/development/docker-compose.yml, caddy/development/Caddyfile"
          target: ${{ secrets.DOCKER_COMPOSE_YAML_PATH }}
          strip_components: 2

      - name: ssh to server and deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -euo pipefail
            cd ${{ secrets.DOCKER_COMPOSE_YAML_PATH }}

            docker compose pull aics-api aics-admin aics-auth
            docker compose --env-file ${{ secrets.ENVIRONMENT_PATH }} up -d aics-api aics-admin aics-auth
